name: nora-s-flora
services:
  php:
    build: .
    depends_on:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "student"
      MYSQL_PASSWORD: "veiligwachtwoord"
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysqltmp:/tmp
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql

